FROM node:18.12.0-alpine as builder
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
COPY tests/ui-e2e /app/tests/ui-e2e
COPY packages/strings /app/packages/strings
# RUN cd /app/tests/ui-e2e && yarn install --production
RUN yarn install --production

FROM cypress/included:13.2.0 as final
WORKDIR /app
COPY --from=builder ./app/tests/ui-e2e .
COPY --from=builder /app/packages/strings .
RUN cypress run
